apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spinnaker-system
resources:
  - base-ingress-deck.yml
  - base-ingress-gate.yml
patchesStrategicMerge:
  - patch-ingress-deck.yml
  - patch-ingress-gate.yml