apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spinnaker-operator
images:
  - name: armory/armory-operator
    newTag: 0.4.0
  - name: armory/halyard-armory
    newTag: operator-0.5.0-rc3
resources:
  - base-deployment.yml
  - base-halyard-config-map.yml
  - base-role.yml
  - base-role-binding.yml
  - base-service-account.yml
patchesStrategicMerge:
  - patch-deployment-replicas.yml
  - patch-deployment-node-selector.yml
