apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base-cert-manager-resources.yml
patchesStrategicMerge:
  - patch-cert-manager-deployments-replicas.yml
  - patch-cert-manager-deployments-node-selectors.yml