apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration.  This is required and must be changed using the patch file to a valid email address
    # so that Let's Encrypt can send notifications about expiring certificates and issues with the account.
    email: johndoe@example.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx