apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base-cert-manager-http-cluster-issuer-prod.yml
  - base-cert-manager-http-cluster-issuer-staging.yml
patchesStrategicMerge:
  - patch-cert-manager-http-cluster-issuer-prod.yml
  - patch-cert-manager-http-cluster-issuer-staging.yml